{
	"version": 1484494301,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/ground.png",
		"images/foreground.png",
		"images/sprite-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/ground2-sheet0.png",
		"images/obstacle-sheet0.png",
		"images/mapinguari-sheet0.png",
		"images/mapinguari-sheet1.png",
		"images/mapinguari-sheet2.png",
		"images/water-sheet0.png",
		"images/splash-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/palmeira-sheet0.png",
		"images/cacho-sheet0.png",
		"media/night_sounds_-_crickets-lisa_redfern-591005346.m4a",
		"media/night_sounds_-_crickets-lisa_redfern-591005346.ogg",
		"media/grunts (as punched)  male.m4a",
		"media/grunts (as punched)  male.ogg",
		"media/creature breath 02.m4a",
		"media/creature breath 02.ogg",
		"media/screams male 02.m4a",
		"media/screams male 02.ogg",
		"media/creature growl 07.m4a",
		"media/creature growl 07.ogg",
		"media/wind.m4a",
		"media/wind.ogg",
		"media/açaí3.m4a",
		"media/açaí3.ogg",
		"media/ffxv_-_dungeon_theme.m4a",
		"media/ffxv_-_dungeon_theme.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}